allow_site:
  [
    "opreviews.anime-pictures.net",
    "anime-pictures.net",
    "www.pixivision.net",
    "i.pximg.net",
    "www.pixiv.net",
    "safebooru.org",
    "img.booru.org",
    "danbooru2.booru.org",
  ]
proxy:
  http: "127.0.0.1:7425"

limit_page: 2
root_folder: "../imgs"
